// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUWZd34n9YxjLYu2X1fscdwfIPwdZHqhI',
    appId: '1:807528317019:web:71ce83a7a83d30a6297f7e',
    messagingSenderId: '807528317019',
    projectId: 'auth-test-d55bc',
    authDomain: 'auth-test-d55bc.firebaseapp.com',
    storageBucket: 'auth-test-d55bc.appspot.com',
    measurementId: 'G-KPJQRF2JRY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFcLTSFb5YGYiy8C4FUtzq7HoY1COaxOo',
    appId: '1:807528317019:android:4b99e91e8c25ed7d297f7e',
    messagingSenderId: '807528317019',
    projectId: 'auth-test-d55bc',
    storageBucket: 'auth-test-d55bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDwoeknay3atOAnPEbuCxNBsy0XtZC2JfI',
    appId: '1:807528317019:ios:6316005bf712306e297f7e',
    messagingSenderId: '807528317019',
    projectId: 'auth-test-d55bc',
    storageBucket: 'auth-test-d55bc.appspot.com',
    iosClientId: '807528317019-sssaj52gmv588mb9jaktekls5vk050ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDwoeknay3atOAnPEbuCxNBsy0XtZC2JfI',
    appId: '1:807528317019:ios:6316005bf712306e297f7e',
    messagingSenderId: '807528317019',
    projectId: 'auth-test-d55bc',
    storageBucket: 'auth-test-d55bc.appspot.com',
    iosClientId: '807528317019-sssaj52gmv588mb9jaktekls5vk050ja.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterAuth',
  );
}
